In [1]:
import sys
!{sys.executable} -m pip install numpy

In [3]:
import numpy

In [4]:
print(numpy.__version__)

1.19.4


In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.19.4


# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [7]:
Array= np.arange(2, 50, 3)
print(Array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [8]:
list1=[1,2,4,3,5]
list2=[6,8,7,9,10]
arr1=np.array(list1)
print(arr1)
arr2=np.array(list2)
print(arr2)

[1 2 4 3 5]
[ 6  8  7  9 10]


In [9]:
arr3=np.concatenate((arr1, arr2), axis=0)
print(arr3)

[ 1  2  4  3  5  6  8  7  9 10]


In [10]:
print(np.sort(arr3))

[ 1  2  3  4  5  6  7  8  9 10]


# Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [11]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)
 

No. of dimensions:  2
Size of array:  6


#  Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [13]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [14]:
 # You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. 
 # For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [15]:
# for a column vector, you can insert an axis along the second dimension:

col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [16]:
# You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

# For example, if you start with this array:

a = np.array([1, 2, 3, 4, 5, 6])
a.shape  

(6,)

In [17]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [18]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack() 

In [19]:
# hstack()

f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [20]:
# vstack()

f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


# Questions 6:

How to get unique items and counts of unique items?

USE set() AND len() TO COUNT UNIQUE VALUES IN A LIST
Call set(*args) with the list as *args to convert the list to a set of unique values. 
Call len(*args) with this new set as *args to return its length, which is the number of unique values.

In [21]:
# for example:

a_list = [1, 1, 2, 2, 3]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

3
